### ISSUE TITLE
error: Exception: Some model files might be missing

### ISSUE THREAD

**Issue by tmrnvcome** [VinAIResearch/MISCA#5]
Hi I tried to train MISCA from scratch but there seems to be missing files. May I know if anyone has managed to resolve this n how?
![Screenshot from 2024-02-08 19-06-51](https://github.com/VinAIResearch/MISCA/assets/134356965/e9ac0436-36b1-47b3-8695-a309c8636444)

**Comment by thinhphp** [comment]
Hi, 
Thanks for your interest in our work! We have updated the code to save the checkpoint, it will save only the state_dict of the model instead of the entire model object. Hope it is helpful for you.
