### ISSUE TITLE
issue in predict.py while loading the trained model no config.json file 

### ISSUE THREAD

**Issue by manishhnnegi** [VinAIResearch/MISCA#6]
while loading model its not able to load model due to no config.json file present in the generated model directory.

OSError: misca does not appear to have a file named config.json. Checkout 'https://huggingface.co/misca/main' for available files.
also after loading model while prediction its asking for sequence_length and heads which is not present in the inputs dictionary.

**Comment by tmrnvcome** [comment]
i have the same issue too.

**Comment by thinhphp** [comment]
Hi, we have updated the predict.py file. You should set hyper-parameters the same as training, and have the checkpoint file (model.bin) in model_dir argument.

**Comment by tmrnvcome** [comment]
Hi. What about line 231,

  *if 'bert' in self.args.model_type*:

This has to be changed to '*roberta*' instead right?

*  if 'roberta' in self.args.model_type:*

Because your code uses *lstm* and *roberta* only.


Regards
Beatrice

**Comment by thinhphp** [comment]
Yes, you can change it to 'roberta' in this case, but our code can be used with other BERT-based PLMs.
