### ISSUE TITLE
predict.py line 29 missing slot_hier, and missing 2 required positional arguments

### ISSUE THREAD

**Issue by tmrnvcome** [VinAIResearch/MISCA#7]
Hi, can I check if line 29 of _predict.py_ has a **missing attribute**? 

Also, when i try to run predict.py with this command
`python predict.py --input_file ./data/sample_pred_in.txt --output_file ./data/sample_pred_out.txt --model_dir ./dir_newmodel_3`

i get this error
**TypeError: JointRoberta.forward() missing 2 required positional arguments: 'heads' and 'seq_lens'**

**Comment by thinhphp** [comment]
Hi, we have updated the predict.py file. You should set hyper-parameters the same as training, and have the checkpoint file (`model.bin`) in `model_dir` argument.
