### ISSUE TITLE
May I ask if the Overall (ACC) in the paper is this one？

### ISSUE THREAD

**Issue by TracyYannn** [VinAIResearch/MISCA#9]
Hello, I am very interested in your research work.
![整体精度](https://github.com/VinAIResearch/MISCA/assets/145429002/606e0bf5-d3d0-42a7-9d6b-a6f095e29afe)
May I ask if the Overall (ACC) in the paper is the semantics_frame_acc in the experiment？

**Comment by thinhphp** [comment]
Yes it is
